language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: ruby-head  # travis broken
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
