language: ruby
rvm:
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
